---
apiVersion: v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/timeout: 4m
    template.openshift.io/expose-uri: http://{.spec.host}{.spec.path}
  name: {{ JENKINS_APPNAME }}
  labels:
    app: {{ JENKINS_APPNAME }}
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: {{ JENKINS_APPNAME }}
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    template.alpha.openshift.io/wait-for-ready: "true"
  name: {{ JENKINS_APPNAME }}
spec:
  replicas: 1
  selector:
    name: {{ JENKINS_APPNAME }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: {{ JENKINS_APPNAME }}
    spec:
      containers:
      - capabilities: {}
        env:
        - name: OPENSHIFT_ENABLE_OAUTH
          value: "true"
        - name: OPENSHIFT_ENABLE_REDIRECT_PROMPT
          value: "true"
        - name: DISABLE_ADMINISTRATIVE_MONITORS
          value: "false"
        - name: KUBERNETES_MASTER
          value: https://kubernetes.default:443
        - name: KUBERNETES_TRUST_CERTIFICATES
          value: "true"
        - name: JENKINS_SERVICE_NAME
          value: {{ JENKINS_APPNAME }}
        - name: JNLP_SERVICE_NAME
          value: jenkins-jnlp
        - name: ENABLE_FATAL_ERROR_LOG_FILE
          value: "false"
        image: {{ JENKINS_IMAGE }}
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 420
          periodSeconds: 360
          timeoutSeconds: 240
        name: jenkins
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 3
          timeoutSeconds: 240
        resources:
          limits:
            memory: {{ JENKINS_MEMORY_LIMIT }}
        securityContext:
          capabilities: {}
          privileged: false
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /var/lib/jenkins
          name: {{ JENKINS_PV }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccountName: {{ JENKINS_APPNAME }}
      volumes:
      - name: {{ JENKINS_PV }}
        persistentVolumeClaim:
          claimName: {{ JENKINS_PV }}
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - jenkins
      from:
        kind: ImageStreamTag
        name: {{ JENKINS_APPNAME }}:{{ JENKINS_VERSION }}
      lastTriggeredImage: ""
    type: ImageChange
  - type: ConfigChange
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.jenkins: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"{{ JENKINS_APPNAME }}"}}'
  name: {{ JENKINS_APPNAME }}
---
apiVersion: v1
groupNames: null
kind: RoleBinding
metadata:
  name: {{ JENKINS_APPNAME }}_edit
roleRef:
  name: edit
subjects:
- kind: ServiceAccount
  name: {{ JENKINS_APPNAME }}
apiVersion: v1
kind: Service
metadata:
  name: 
spec:
  ports:
  - name: agent
    nodePort: 0
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    name: {{ JENKINS_APPNAME }}
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/dependencies: '[{"name": "jenkins-jnlp",
      "namespace": "", "kind": "Service"}]'
    service.openshift.io/infrastructure: "true"
  name: {{ JENKINS_APPNAME }}
spec:
  ports:
  - name: web
    nodePort: 0
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    name: {{ JENKINS_APPNAME }}
  sessionAffinity: None
  type: ClusterIP
