---
apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    description: Keeps track of changes in the application image
  name: jenkins-agent-maven-35-rhel7
  app: jenkins-agent-maven-35-rhel7
---
kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "jenkins-agent-maven-bc"
spec:
  runPolicy: "Serial" 
  source:
    type: Dockerfile
    dockerfile: "FROM {{ JENKINS_AGENT_MAVEN_IMAGE }}\nUSER root\nRUN yum -y install skopeo && yum clean all\nUSER 1001"
  output:
    to:
      kind: ImageStreamTag
      name: jenkins-agent-maven-35-rhel7:v3.11 
  strategy:
    type: Docker
